### ISSUE TITLE
UI: [Bug] Column widths for Filtered and Unfiltered Lists are not the same

### ISSUE THREAD

**Issue by elliot-tang** [AY2425S1-CS2103T-T09-4/tp#143]
![image](https://github.com/user-attachments/assets/ec4cd1d6-84a1-4f7e-b6a8-172fd7572983)
![image](https://github.com/user-attachments/assets/bc57fc06-18a1-40f5-b982-6de1c07f8b2d)

**Comment by ckclion** [comment]
Limitations of having a scrollbar
