### ISSUE TITLE
[PE-D][Tester E] Unclear validation of parameters in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-4/tp#283]
User Guide does not reflect certain input validations, ie Name being alphanumeric, case sensitive; Tags not allowing for spaces.

![image.png](https://raw.githubusercontent.com/colinhia/ped/main/files/f2497584-3aa4-483c-b5e0-6a851c4334ee.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: colinhia/ped#7

**Comment by lutfir-cpu** [comment]
Resolved with #333
